<?php

/**
 * Implements hook_install().
 */
function lightning_page_install() {
  $module_handler = Drupal::moduleHandler();

  $modules = [];

  if ($module_handler->moduleExists('lightning_workflow')) {
    array_push($modules, 'lightning_workflow');
  }
  if ($module_handler->moduleExists('menu_ui')) {
    array_push($modules, 'menu_ui');
  }

  if ($modules) {
    lightning_page_modules_installed($modules);
  }
}
